# Default values for mosquitto-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eclipse-mosquitto
  tag: 1.6.5
  pullPolicy: IfNotPresent
  pullSecrets: []

nameOverride: "mosquitto"
fullnameOverride: ""

# TODO add useful probes
#readinessProbe:
  # httpGet:
  #   port: http
  # initialDelaySeconds: 5
  # periodSeconds: 10
  
# livenessProbe: 
  # httpGet:
  #   port: http
  # initialDelaySeconds: 120
  # periodSeconds: 10

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  storageSize: 8Gi
  #storageClassName name of the storage class, default is standard

nodeSelector: {}

tolerations: []

affinity: {}

config: {} #contains configuration options of the mosquitto broker

password: 
  enabled: false # enable password for the mosquitto broker
  #value:  # if password set enabled to true: password for the mosquitto broker
