apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto-helm.fullname" . }}-password
  labels:
{{ include "mosquitto-helm.labels" . | indent 4 }}
data:
  passwd: |-
{{- if .Values.password }}
{{ .Values.password | indent 4 }}
{{- end -}}