apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto-helm.fullname" . }}-config
  labels:
{{ include "mosquitto-helm.labels" . | indent 4 }}
data:
  mosquitto.conf: |-
{{- if .Values.config }}
{{ .Values.config | indent 4 }}
{{- end -}}