{{- if .Values.password.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto-helm.fullname" . }}-password
  labels:
{{ include "mosquitto-helm.labels" . | indent 4 }}
data:
  passwd: |-
{{ include "mosquitto-helm.passwordSecret" . | indent 4 }}
{{- end -}}