{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mosquitto-helm.fullname" . }}
  labels:
{{ include "mosquitto-helm.labels" . | indent 4 }}
spec:
  accessModes:
{{ .Values.persistence.accessModes | toYaml | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize | quote }}

{{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
{{- else }}
  storageClassName: standard
{{- end }}

{{- if .Values.persistence.persistenceVolumeLabel }}
  selector:
    matchLabels:
      volume: {{ .Values.persistence.persistenceVolumeLabel | quote }}
{{- end }}

{{- end }}
